### ISSUE TITLE
Discard index.ts files for nested feature modules

### ISSUE THREAD

**Issue by msleiman2** [mrahhal/vscode-ng-tooling#1]
This tool does not ignore the index.ts files inside module's children.

Let's say that I have a feature **module A**, and this module (A) has a child **module B** that should has it's own declarations, obviously. 

So, when I run the generate command it should import all the declaration of **module A** in {ModuleA.index.ts} and all the declaration of **module B** in in {ModuleB.index.ts}.

It does most of it's job correctly, but the problem is why it re-imports the declarations registered in all the index.ts files of **module B** inside {ModuleA.index.ts}.

**Comment by mrahhal** [comment]
Sounds good. It'll need a bit of restructuring to detect nested modules properly.

**Comment by mrahhal** [comment]
This is resolved in version `0.6.0`. Try it out and let me know if it works for you!

**Comment by msleiman2** [comment]
Thank you, it worked 👯
